<?php

/**
 * ShopEx licence
 *
 * @copyright  Copyright (c) 2005-2010 ShopEx Technologies Inc. (http://www.shopex.cn)
 * @license  http://ecos.shopex.cn/ ShopEx License
 */

return array(
    'columns' => array(
        'activity_id' => array(
            'type' => 'number',
            'required' => true,
            'autoincrement' => true,
            'in_list' => false,
            'label' => app::get('syspromotion')->_('规则id'),
            'comment' => app::get('syspromotion')->_('规则id'),
        ),
        'name' => array(
            'type' => 'string',
            'length' => 100,
            'required' => true,
            'default' => '',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filterdefault' => true,
            'is_title' => true,
            'label' => app::get('syspromotion')->_('规则名称'),
            'comment' => app::get('syspromotion')->_('规则名称'),
        ),
        'description' => array(
            'type' => 'text',
            'required' => false,
            'default' => '',
            'editable' => false,
            'in_list' => true,
            'filterdefault' => true,
            'label' => app::get('syspromotion')->_('规则描述'),
            'comment' => app::get('syspromotion')->_('规则描述'),
        ),
        'release_time' => array(
            'type' => 'time',
            'default' => 0,
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filterdefault' => true,
            'label' => app::get('syspromotion')->_('发布时间'),
            'comment' => app::get('syspromotion')->_('发布时间'),
        ),
        'begin_time' => array(
            'type' => 'time',
            'default' => 0,
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filterdefault' => true,
            'label' => app::get('syspromotion')->_('开始时间'),
            'comment' => app::get('syspromotion')->_('开始时间'),
        ),
        'end_time' => array(
            'type' =>'time',
            'default' => 0,
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filterdefault' => true,
            'label' => app::get('syspromotion')->_('结束时间'),
            'comment' => app::get('syspromotion')->_('结束时间'),
        ),
        'status' => array(
            'type' => 'bool',
            'default' => 0,
            'in_list' => true,
            'editable' => false,
            'filterdefault' => true,
            'default_in_list' => true,
            'label' => app::get('syspromotion')->_('状态'),
            'comment' => app::get('syspromotion')->_('状态'),
        ),
        'remind_way' => array(
            'type' => 'serialize',
            'default_in_list' => false,
            'in_list' => false,
            'label' => app::get('syspromotion')->_('提醒方式'),
            'comment' => app::get('syspromotion')->_('提醒方式'),
        ),
        'remind_time' => array(
            'type' => 'number',
            'default' => 0,
            'default_in_list' => true,
            'in_list' => true,
            'label' => app::get('syspromotion')->_('提前提醒时间'),
            'comment' => app::get('syspromotion')->_('提前提醒时间'),
        ),
        'limit' => array(
            'type' =>'number',
            'default' => 0,
            'default_in_list' => false,
            'in_list' => true,
            'label' => app::get('syspromotion')->_('限购数量'),
            'comment' => app::get('syspromotion')->_('限购数量'),
            'width' => 100,
        ),
        'cdown' => array(
            'type' => 'bool',
            'default' => 1,
            'default_in_list' => false,
            'in_list' => false,
            'label' => app::get('syspromotion')->_('是否显示倒计时'),
            'comment' => app::get('syspromotion')->_('是显示否倒计时'),
        ),
        'timeout' => array(
            'type' => 'number',
            'default' => 0,
            'label' => app::get('syspromotion')->_('超时时间'),
            'comment' => app::get('syspromotion')->_('超时时间'),
        ),
        'initial_num' => array(
            'type' => 'number',
            'default' => 0,
            'label' => app::get('syspromotion')->_('初始销售量'),
            'comment' => app::get('syspromotion')->_('初始销售量'),
        ),
        'type_id' => array(
            'type' => 'number',
            'default_in_list' => true,
            'in_list' => true,
            'label' => app::get('syspromotion')->_('促销类型 '),
            'comment' => app::get('syspromotion')->_('促销类型'),
            'order' => 4,
            'width' => 80,
        ),
        'promotion_pro' => array(
            'type' => 'serialize',
            'default_in_list' => false,
            'in_list' => false,
            'label' => app::get('syspromotion')->_('促销商品组合'),
            'comment' => app::get('syspromotion')->_('促销商品组合 '),
        ),
    ),
    'primary' => 'activity_id',
);
