<?php
return  array(
    'columns'=>array(
        'oid'=>array(
            'type' => 'string',
            'length' => 20,
            'label' => app::get('syshdtj')->_('订单编号'),
            'comment' => app::get('syshdtj')->_('订单编号'),
            'in_list' => true,
            'default_in_list' => true,
            'unsigned' => true,
            'required' => true,
            'order' => 0,
        ),
        'payed_time' => array (
            'type' => 'time',
            'in_list' => true,
            'default_in_list' => true,
            'label' => app::get('syshdtj')->_('支付完成时间'),
            'comment' => app::get('syshdtj')->_('支付完成时间'),
        ),
        'user_id' => array(
            'type' => 'table:account@sysuser',
            'required' => true,
            'comment' => app::get('syshdtj')->_('买家id'),
        ),
        'order_from' => array( //可以是 产品订单、店铺开店、演唱会门票等
            'type' => 'string',
            'length' => 45,
            'in_list' => true,
            'default_in_list' => true,
            'label' => app::get('syshdtj')->_('订单来源'),
            'comment' => app::get('syshdtj')->_('订单来源'),
            'order' => 1,
        ),
        'payment_id' => array (
            'type' => 'string',
            'length' => 20,
            'required' => true,
            'default' => '',
            'in_list' => true,
            'default_in_list' => true,
            'label' => app::get('syshdtj')->_('支付单号'),
            'comment' => app::get('syshdtj')->_('支付单号'),
        ),
        'bank' => array (
            'type' => 'string',
            'length' => 50,
            'in_list' => true,
            'default_in_list' => true,
            'label' => app::get('syshdtj')->_('收款银行'),
            'comment' => app::get('syshdtj')->_('收款银行'),
        ),
        'title' => array(
            'type' => 'string',
            'length' => 60,
            'required' => true,
            'default' => '',
            'in_list' => true,
            'default_in_list' => true,
            'label' => app::get('syshdtj')->_('商品'),
            'comment' => app::get('syshdtj')->_('商品'),
            'order' => 2,
        ),
        'spec_nature_info' => array (
            'type' => 'text',
            'in_list' => true,
            'default_in_list' => true,
            'label' => app::get('syshdtj')->_('描述'),
            'comment' => app::get('syshdtj')->_('描述'),
            'order' => 3,
        ),
        'price' => array(
            'type' => 'money',
            'required' => true,
            'default' => '0',
            'label' => app::get('syshdtj')->_('售价'),
            'comment' => app::get('syshdtj')->_('售价'),
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 4,
        ),
        'num' => array(
            'type' => 'number',
            'comment' => app::get('syshdtj')->_('数量'),
        ),
        'payment' => array(
            'type' => 'money',
            'required' => true,
            'default' => '0',
            'label' => app::get('syshdtj')->_('实付金额'),
            'comment' => app::get('syshdtj')->_('实付金额'),
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 5,
        ),
        'area' => array (
                'label' => app::get('syshdtj')->_('消费者所在地'),
                'comment' => app::get('syshdtj')->_('消费者所在地'),
                'width' => 110,
                'type' => 'string',
                'length' => 55,
                'editable' => false,
                'filtertype' => 'yes',
                'filterdefault' => 'true',
                'in_list' => true,
                'default_in_list' => false,
        ),
        'shop_area' => array (
            'label' => app::get('syshdtj')->_('供应商所在地'),
            'comment' => app::get('syshdtj')->_('供应商所在地'),
            'width' => 110,
            'type' => 'string',
            'length' => 55,
            'editable' => false,
            'filtertype' => 'yes',
            'filterdefault' => 'true',
            'in_list' => true,
            'default_in_list' => false,
        ),
        'shop_id' => array(
            'type' => 'table:shop@sysshop',
            'required' => true,
            'comment' => app::get('syshdtj')->_('所属供应商'),
        ),
        'cost_price' => array(
            'type' => 'money',
            'label' => app::get('syshdtj')->_('供应商提成'),
            'comment' => app::get('syshdtj')->_('供应商提成'),
            'in_list' => true,
            'default' => '0',
            'default_in_list' => false,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 6,
        ),
        'topd_id' => array(
            'type' => 'number',
            'required' => true,
            'comment' => app::get('syshdtj')->_('所属分销商'),
        ),
        'topd_price' => array(
            'type' => 'money',
            'label' => app::get('syshdtj')->_('分销商提成'),
            'comment' => app::get('syshdtj')->_('分销商提成'),
            'in_list' => true,
            'default' => '0',
            'default_in_list' => false,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 7,
        ),
        'gszx_id' => array(
            'type' => 'number',
            'required' => true,
            'comment' => app::get('syshdtj')->_('供应商所在县'),
        ),
        'gszx_price' => array(
            'type' => 'money',
            'label' => app::get('syshdtj')->_('所属供所在县提成'),
            'comment' => app::get('syshdtj')->_('所属供所在县提成'),
            'in_list' => true,
            'default' => '0',
            'default_in_list' => false,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 7,
        ),
        'szs_id' => array(
            'type' => 'number',
            'required' => true,
            'comment' => app::get('syshdtj')->_('消费者所属省'),
        ),
        'szs_price' => array(
            'type' => 'money',
            'label' => app::get('syshdtj')->_('所属省提成'),
            'comment' => app::get('syshdtj')->_('所属省提成'),
            'in_list' => true,
            'default' => '0',
            'default_in_list' => false,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 7,
        ),
        'szshi_id' => array(
            'type' => 'number',
            'required' => true,
            'comment' => app::get('syshdtj')->_('消费者所属市'),
        ),
        'szshi_price' => array(
            'type' => 'money',
            'label' => app::get('syshdtj')->_('所属市提成'),
            'comment' => app::get('syshdtj')->_('所属市提成'),
            'in_list' => true,
            'default' => '0',
            'default_in_list' => false,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 7,
        ),
        'szx_id' => array(
            'type' => 'number',
            'required' => true,
            'comment' => app::get('syshdtj')->_('消费者所属县'),
        ),
        'szx_price' => array(
            'type' => 'money',
            'label' => app::get('syshdtj')->_('所属县提成'),
            'comment' => app::get('syshdtj')->_('所属县提成'),
            'in_list' => true,
            'default' => '0',
            'default_in_list' => false,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 7,
        ),
        'hdvg_price' => array(
            'type' => 'money',
            'label' => app::get('syshdtj')->_('恒大微购'),
            'comment' => app::get('syshdtj')->_('恒大微购'),
            'in_list' => true,
            'default' => '0',
            'default_in_list' => false,
            'filtertype' => 'number',
            'filterdefault' => true,
            'order' => 7,
        ),
    ),
    'primary' => 'oid',
    'comment' => app::get('syshdtj')->_('详细订单提成'),
);
