<?php
return  array(
    'columns'=>array(
        'oid'=>array(
            'type' => 'table:order@syshdtj',
            'label' => app::get('syshdtj')->_('订单编号'),
            'comment' => app::get('syshdtj')->_('订单编号'),
            'in_list' => true,
            'default_in_list' => true,
            'unsigned' => true,
            'required' => true,
            'order' => 0,
        ),
        'order_from' => array( //可以是 产品订单、店铺开店、演唱会门票等
            'type' => 'table:order@syshdtj',
            'length' => 45,
            'in_list' => true,
            'default_in_list' => true,
            'label' => app::get('syshdtj')->_('订单来源'),
            'comment' => app::get('syshdtj')->_('订单来源'),
            'order' => 1,
        ),
        'statusj' => array (
            'type' => array (
                'succ' => app::get('syshdtj')->_('已结算'),
                'cancel' => app::get('syshdtj')->_('未结算'),
            ),
            'default' => 'cancel',
            'required' => true,
            'label' => app::get('syshdtj')->_('结算状态'),
            'comment' => app::get('syshdtj')->_('结算状态'),
        ),
        'statusjtime' => array (
            'type' => 'text',
            'default' => '',
            'label' => app::get('syshdtj')->_('结算状态'),
            'comment' => app::get('syshdtj')->_('结算状态'),
        ),
        'status' => array (
                'type' => array (
                        'succ' => app::get('syshdtj')->_('已日结'),
                        'cancel' => app::get('syshdtj')->_('未结算'),
                ),
                'default' => 'cancel',
                'required' => true,
                'label' => app::get('syshdtj')->_('日结状态状态'),
                'comment' => app::get('syshdtj')->_('日结状态状态'),
                'width' => 75,
                'editable' => false,
                'filtertype' => 'yes',
                'hidden' => true,
                'filterdefault' => true,
                'in_list' => true,
                'default_in_list' => true,
        ),
        'statustime' => array (
            'type' => 'text',
            'default' => '',
            'label' => app::get('syshdtj')->_('日结时间'),
            'comment' => app::get('syshdtj')->_('日结时间'),
            'width' => 270,
            'editable' => false,
            'in_list' => true,
        ),
        'statusm' => array (
            'type' => array (
                'succ' => app::get('syshdtj')->_('已月结'),
                'cancel' => app::get('syshdtj')->_('未结算'),
            ),
            'default' => 'cancel',
            'required' => true,
            'label' => app::get('syshdtj')->_('月结状态状态'),
            'comment' => app::get('syshdtj')->_('月结状态状态'),
            'width' => 75,
            'editable' => false,
            'filtertype' => 'yes',
            'hidden' => true,
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
        ),
        'statusmtime' => array (
            'type' => 'text',
            'default' => '',
            'label' => app::get('syshdtj')->_('月结时间'),
            'comment' => app::get('syshdtj')->_('月结时间'),
            'width' => 270,
            'editable' => false,
            'in_list' => true,
        ),
    ),
    'primary' => 'oid',
    'comment' => app::get('syshdtj')->_('订单结算状态'),
);
